# Generated by Django 4.1.2 on 2022-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
