# Generated by Django 4.1.2 on 2022-10-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='33c7b0c5-fefb-40b6-9118-f0d7b7f5d1e3', editable=False, primary_key=True, serialize=False),
        ),
    ]
