# Generated by Django 4.1.2 on 2022-10-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='801d8c30-c1f7-49d8-9ac3-c81de7a82507', editable=False, primary_key=True, serialize=False),
        ),
    ]
