# Generated by Django 4.1.2 on 2022-10-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='e3d1d18d-1695-430f-8c38-8f8f746b9499', editable=False, primary_key=True, serialize=False),
        ),
    ]
