# Generated by Django 4.1.2 on 2022-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(blank=True, default=''),
        ),
    ]
