# Generated by Django 4.1.2 on 2022-10-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='32a98e36-aec8-47db-acec-127590e75a07', editable=False, primary_key=True, serialize=False),
        ),
    ]
