# Generated by Django 4.1.2 on 2022-10-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='38009b7e-42c5-4b22-8c6c-18298ee1641b', editable=False, primary_key=True, serialize=False),
        ),
    ]
