# Generated by Django 4.1.2 on 2022-10-19 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_is_active_author_is_admin_author_last_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
