# Generated by Django 4.1.2 on 2022-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(blank=True, default='c7423ef4-57c8-418b-92a9-4a25a43e0334', editable=False, primary_key=True, serialize=False),
        ),
    ]
