# Generated by Django 4.1.2 on 2022-10-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_author_groups_author_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
