<<<<<<< HEAD
from django.db import models

# Create your models here.
class Node(models.Model):

    hostName = models.URLField(max_length=200)       # NOTE, remote host name

    # maybe some fields required for an authentication connect
    authUsername = models.CharField(max_length=200)  #  NOTE, this is username generated by us for them
    authPassword = models.CharField(max_length=200)  #  NOTE, this is password generated by us for them
    

    def __str__(self):
            return 'hostName: %s' % (self.hostName)
=======
from django.db import models

class Node(models.Model):

    host = models.URLField(max_length=200)       # NOTE the remote node's API endpoint

    # username and password fields should be determined between
    # the two nodes
    username = models.CharField(max_length=200)  
    password = models.CharField(max_length=200)  
    

    def __str__(self):
            return 'host_api_url: %s' % (self.host)
>>>>>>> origin/main
