from django.db import models

# Create your models here.
class Node(models.Model):

    host = models.URLField(max_length=200)       # NOTE, remote host name

    # maybe some fields required for an authentication connect
    username = models.CharField(max_length=200)  #  NOTE, this is username generated by us for them
    password = models.CharField(max_length=200)  #  NOTE, this is password generated by us for them
    

    def __str__(self):
            return 'hostName: %s' % (self.hostName)