# Generated by Django 4.1.2 on 2022-10-22 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
