# Generated by Django 4.1.2 on 2022-11-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
