# Generated by Django 4.1.2 on 2022-11-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='hostName',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='authPassword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='authUsername',
            new_name='username',
        ),
    ]
