# Generated by Django 4.1.2 on 2022-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
