# Generated by Django 4.1.2 on 2022-10-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
