# Generated by Django 4.1.2 on 2022-10-23 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('followers', '0001_initial'),
        ('post', '0001_initial'),
        ('comments', '0001_initial'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('type', models.CharField(default='inbox', editable=False, max_length=10)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('follow_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests', to='followers.friendrequest')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='like.like')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
