# Generated by Django 4.1.2 on 2022-10-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='empty comment', max_length=200),
        ),
    ]
