# Generated by Django 4.1.2 on 2022-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/markdown', max_length=200),
        ),
    ]
